import React, { useState } from "react";
import { orchestratorApi } from "../api/orchestratorClient";
import "../styles/reactiveEmail.css";

export function ReactiveEmail() {
  const [simulationState, setSimulationState] = useState("idle"); // idle, loading, completed, failed
  const [errorMsg, setErrorMsg] = useState("");
  const [sessionInfo, setSessionInfo] = useState(null);
  const [emailDetails, setEmailDetails] = useState(null);
  const [planSteps, setPlanSteps] = useState([]);
  const [activeTab, setActiveTab] = useState("all");

  const runSimulation = async () => {
    setSimulationState("loading");
    setErrorMsg("");
    setEmailDetails(null);
    setPlanSteps([]);
    
    try {
      // Trigger simulation for CUST-1001
      const res = await orchestratorApi.simulateOutage("CUST-1001");
      
      // Parse steps and results
      const steps = res.steps || {};
      const plan = res.plan || {};
      const stepsList = [];
      let mockEmail = null;

      // Extract details from plan steps and step outputs
      Object.entries(steps).forEach(([stepId, stepData]) => {
        stepsList.push({
          id: stepId,
          agent: stepData.agent || "Unknown Agent",
          objective: stepData.objective || "Analysis",
          status: stepData.status || "completed",
          output: stepData.output || "",
          error: stepData.error || ""
        });

        // Find email details from the email agent
        if (stepData.agent === "email_notification_agent" && stepData.output) {
          mockEmail = typeof stepData.output === "string" 
            ? JSON.parse(stepData.output) 
            : stepData.output;
        }
      });

      // Fallback: If OpenAI didn't output email JSON but structured text was generated
      if (!mockEmail && res.response) {
        mockEmail = {
          recipient: "james.doe@example.com",
          subject: "⚠️ NexusGas Service Alert: Outage Detected & Action Plan",
          body: res.response,
          sent_at: new Date().toISOString(),
          status: "sent"
        };
      }

      setPlanSteps(stepsList);
      setEmailDetails(mockEmail);
      setSessionInfo(res);
      setSimulationState("completed");
    } catch (err) {
      console.error("Simulation failed:", err);
      setErrorMsg(err.message || "Failed to complete simulation pipeline.");
      setSimulationState("failed");
    }
  };

  return (
    <div className="reactive-email-container">
      <div className="reactive-email-header">
        <div>
          <h1>Reactive Alerts Dashboard</h1>
          <p className="subtitle">
            Simulate automated proactive and reactive notifications generated by backend multi-agent workflows.
          </p>
        </div>
        <button
          type="button"
          className={`btn-simulate ${simulationState === "loading" ? "loading" : ""}`}
          onClick={runSimulation}
          disabled={simulationState === "loading"}
        >
          {simulationState === "loading" ? (
            <>
              <span className="spinner-small"></span>
              Simulating Outage...
            </>
          ) : (
            "⚡ Simulate Outage (CUST-1001)"
          )}
        </button>
      </div>

      {simulationState === "failed" && (
        <div className="simulation-alert error">
          <strong>Simulation Interrupted:</strong> {errorMsg}
        </div>
      )}

      <div className="reactive-email-grid">
        {/* LEFT COLUMN: Map & Agent Execution Trace */}
        <div className="reactive-column">
          
          {/* Map Card */}
          <div className="dashboard-card map-card">
            <div className="card-header-clean">
              <h3>📍 Service Outage Map</h3>
              <span className="badge-area">Austin (78712)</span>
            </div>
            
            <div className="map-view-wrapper">
              <svg className="austin-grid-map" viewBox="0 0 500 350">
                {/* Background grid representing city blocks */}
                <path d="M 0,50 L 500,50 M 0,100 L 500,100 M 0,150 L 500,150 M 0,200 L 500,200 M 0,250 L 500,250 M 0,300 L 500,300" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                <path d="M 50,0 L 50,350 M 100,0 L 100,350 M 150,0 L 150,350 M 200,0 L 200,350 M 250,0 L 250,350 M 300,0 L 300,350 M 350,0 L 350,350 M 400,0 L 400,350 M 450,0 L 450,350" stroke="rgba(255,255,255,0.03)" strokeWidth="1" />
                
                {/* Stylized major roads/intersections */}
                <path d="M 50,0 Q 150,150 250,350" stroke="rgba(255,255,255,0.06)" strokeWidth="4" fill="none" />
                <path d="M 0,180 L 500,180" stroke="rgba(255,255,255,0.06)" strokeWidth="4" fill="none" />
                <path d="M 380,0 Q 300,150 420,350" stroke="rgba(255,255,255,0.06)" strokeWidth="3" fill="none" />
                
                {/* Labels for service region */}
                <text x="35" y="165" fill="rgba(255,255,255,0.3)" fontSize="10" fontFamily="sans-serif">I-35 Highway</text>
                <text x="350" y="30" fill="rgba(255,255,255,0.2)" fontSize="11" fontWeight="bold">NORTH AUSTIN</text>
                <text x="60" y="320" fill="rgba(255,255,255,0.2)" fontSize="11" fontWeight="bold">DOWNTOWN</text>
                
                {/* Outage area representation */}
                {simulationState === "completed" || simulationState === "loading" ? (
                  <>
                    {/* Glowing Red Outage Radius */}
                    <circle cx="260" cy="180" r="100" className="outage-overlay-pulse" />
                    <circle cx="260" cy="180" r="100" fill="url(#outageGradient)" opacity="0.4" />
                    
                    {/* Outage boundary outline */}
                    <circle cx="260" cy="180" r="100" stroke="#EF4444" strokeWidth="1.5" strokeDasharray="6,4" fill="none" opacity="0.6" />
                    
                    {/* Outage Center / Substation */}
                    <circle cx="260" cy="180" r="5" fill="#EF4444" />
                    <text x="270" y="184" fill="#EF4444" fontSize="10" fontWeight="bold" fontFamily="sans-serif">Substation 78712</text>
                    
                    {/* Customer Node */}
                    <g transform="translate(220, 160)">
                      <circle cx="0" cy="0" r="8" className="customer-node-pulse" />
                      <circle cx="0" cy="0" r="5" fill="#0A84FF" />
                      <text x="12" y="4" fill="#E2E8F0" fontSize="10" fontWeight="bold" fontFamily="sans-serif">CUST-1001 (James Doe)</text>
                    </g>
                  </>
                ) : (
                  <>
                    {/* Normal/Healthy Map State */}
                    <g transform="translate(220, 160)">
                      <circle cx="0" cy="0" r="5" fill="#10B981" />
                      <text x="10" y="4" fill="rgba(255,255,255,0.5)" fontSize="10" fontFamily="sans-serif">CUST-1001 (Healthy)</text>
                    </g>
                    <text x="180" y="180" fill="rgba(255,255,255,0.25)" fontSize="13" fontFamily="sans-serif">No Active Outages Simulated</text>
                  </>
                )}

                {/* SVG Gradients */}
                <defs>
                  <radialGradient id="outageGradient" cx="50%" cy="50%" r="50%">
                    <stop offset="0%" stopColor="#EF4444" stopOpacity="0.8" />
                    <stop offset="60%" stopColor="#EF4444" stopOpacity="0.3" />
                    <stop offset="100%" stopColor="#EF4444" stopOpacity="0" />
                  </radialGradient>
                </defs>
              </svg>
            </div>
            
            <div className="map-legend">
              <div className="legend-item">
                <span className="legend-dot healthy"></span>
                <span>Active Grid</span>
              </div>
              <div className="legend-item">
                <span className="legend-dot affected"></span>
                <span>Outage Zone (78712)</span>
              </div>
              <div className="legend-item">
                <span className="legend-dot customer"></span>
                <span>Customer Address</span>
              </div>
            </div>
          </div>

          {/* Orchestration Pipeline Details */}
          <div className="dashboard-card pipeline-card">
            <div className="card-header-clean">
              <h3>🤖 Orchestration Pipeline Trace</h3>
              {sessionInfo && (
                <span className="session-tag">Session: {sessionInfo.session_id.slice(0, 8)}</span>
              )}
            </div>
            
            <div className="pipeline-steps-wrapper">
              {simulationState === "idle" && (
                <div className="empty-state-placeholder">
                  Click the simulation button to trigger a multi-agent plan execution.
                </div>
              )}

              {simulationState === "loading" && (
                <div className="pipeline-loading-steps">
                  <div className="loading-step-item">
                    <span className="pulse-loader"></span>
                    <span>Hub Planner generating dependency graph...</span>
                  </div>
                  <div className="loading-step-item-sub">
                    Analyzing active outage registers & weather alert services.
                  </div>
                </div>
              )}

              {simulationState === "completed" && planSteps.length > 0 && (
                <div className="pipeline-steps-list">
                  {planSteps.map((step, index) => {
                    const isOutage = step.agent === "outage_detection_agent";
                    const isWeather = step.agent === "weather_context_agent";
                    const isEmail = step.agent === "email_notification_agent";
                    
                    let agentIcon = "⚙️";
                    let agentColor = "var(--text-tertiary)";
                    if (isOutage) { agentIcon = "⚠️"; agentColor = "#EF4444"; }
                    else if (isWeather) { agentIcon = "🌡️"; agentColor = "#3B82F6"; }
                    else if (isEmail) { agentIcon = "📧"; agentColor = "#10B981"; }

                    return (
                      <div className="pipeline-step-item-complete" key={step.id}>
                        <div className="step-header-row">
                          <div className="step-number">Step {index + 1}</div>
                          <div className="step-agent-badge" style={{ borderColor: agentColor, color: agentColor }}>
                            <span style={{ marginRight: 4 }}>{agentIcon}</span>
                            {step.agent.replace(/_/g, " ")}
                          </div>
                        </div>
                        <div className="step-objective"><strong>Objective:</strong> {step.objective}</div>
                        <div className="step-output-box">
                          {typeof step.output === "object" ? (
                            <pre className="step-output-json">{JSON.stringify(step.output, null, 2)}</pre>
                          ) : (
                            <p className="step-output-text">{step.output}</p>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: Simulated Email Inbox */}
        <div className="reactive-column">
          <div className="dashboard-card inbox-card">
            <div className="card-header-clean">
              <h3>📧 Customer Notification Email</h3>
              {emailDetails && (
                <span className="badge-sent">
                  <span className="badge-dot-green"></span> Sent
                </span>
              )}
            </div>

            <div className="email-client-container">
              {!emailDetails ? (
                <div className="inbox-empty-state">
                  <div className="inbox-icon">📬</div>
                  <h4>No New Notifications</h4>
                  <p>Trigger the outage simulation to generate and dispatch the reactive safety alert email.</p>
                </div>
              ) : (
                <div className="email-message-wrapper">
                  <div className="email-metadata-block">
                    <div className="metadata-row">
                      <span className="meta-label">From:</span>
                      <span className="meta-value"><strong>NexusGas Support Operations</strong> &lt;alerts@nexusgas.com&gt;</span>
                    </div>
                    <div className="metadata-row">
                      <span className="meta-label">To:</span>
                      <span className="meta-value"><strong>James Doe</strong> &lt;{emailDetails.recipient}&gt;</span>
                    </div>
                    <div className="metadata-row">
                      <span className="meta-label">Date:</span>
                      <span className="meta-value">{new Date(emailDetails.sent_at).toLocaleString()}</span>
                    </div>
                    <div className="metadata-row">
                      <span className="meta-label">Subject:</span>
                      <span className="meta-value-subject">{emailDetails.subject}</span>
                    </div>
                  </div>

                  <div className="email-body-content">
                    {/* Render plain text with clean formatting */}
                    {emailDetails.body.split("\n").map((line, idx) => {
                      if (line.startsWith("🔌") || line.startsWith("🌡️") || line.startsWith("📋")) {
                        return <h4 className="email-section-heading" key={idx}>{line}</h4>;
                      }
                      if (line.startsWith("•") || line.startsWith("1.") || line.startsWith("2.") || line.startsWith("3.")) {
                        return <p className="email-list-line" key={idx}>{line}</p>;
                      }
                      return <p className="email-body-line" key={idx}>{line}</p>;
                    })}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
