import React, { useState } from "react";
import { TooltipIcon } from "./Primitives.jsx";

// ── Constants ─────────────────────────────────────────────────────────────────

const FIELD_TYPES = ["string", "number", "boolean", "array", "object"];

const TYPE_COLORS = {
  string:  { bg: "#e0e7ff", color: "#3730a3" },
  number:  { bg: "#dcfce7", color: "#15803d" },
  boolean: { bg: "#fef3c7", color: "#92400e" },
  array:   { bg: "#fce7f3", color: "#9d174d" },
  object:  { bg: "#f0f9ff", color: "#0369a1" },
};

const TIPS = {
  name:        "Exact JSON key name used in the request body. e.g. customer_id, message, query",
  description: "Natural-language hint for the LLM mapper. Be specific about what value to use. e.g. 'The user account number in format ACC-XXXXX extracted from customer context'",
  required:    "Required fields MUST be present — the orchestrator will fail the step if they cannot be inferred. Optional fields are included only when high-confidence data exists.",
  field_type:  "The expected JSON type of this field. The LLM will coerce the value accordingly.",
  default:     "Fallback value used when the LLM cannot infer a value for a required field. Leave blank to fail instead of guessing.",
  nested:      "Define sub-fields for object-type fields. Each sub-field follows the same rules.",
  strict:      "When enabled, any extra fields generated by the LLM are stripped from the output. Recommended for production.",
  json_schema: "Optional JSON Schema for post-mapping validation. The constructed body is validated against this after the LLM runs.",
};

// ── Helper components ─────────────────────────────────────────────────────────

function TypeBadge({ type }) {
  const { bg, color } = TYPE_COLORS[type] || { bg: "#f1f5f9", color: "#334155" };
  return (
    <span style={{ background: bg, color, padding: "1px 7px", borderRadius: 99,
      fontSize: 11, fontWeight: 600 }}>{type}</span>
  );
}

function RequiredIndicator({ required }) {
  if (required) {
    return (
      <span style={{ fontSize: 11, fontWeight: 700, color: "#ef4444",
        background: "#fee2e2", padding: "1px 6px", borderRadius: 99 }}>
        * required
      </span>
    );
  }
  return (
    <span style={{ fontSize: 11, color: "var(--text-muted)",
      background: "var(--c-neutral-bg)", padding: "1px 6px", borderRadius: 99 }}>
      optional
    </span>
  );
}

// ── Single field editor ───────────────────────────────────────────────────────

function FieldEditor({ field, depth = 0, onChange, onRemove, allFieldNames, siblingNames }) {
  const [expanded, setExpanded] = useState(depth === 0);
  const [showNested, setShowNested] = useState(false);

  const set = (k, v) => onChange({ ...field, [k]: v });

  const isDuplicate = siblingNames.filter(n => n === field.name).length > 1;

  const addNestedField = () => {
    const newField = { name: "", description: "", required: true,
      field_type: "string", default: null, nested_fields: [] };
    set("nested_fields", [...(field.nested_fields || []), newField]);
  };

  const updateNested = (i, val) =>
    set("nested_fields", (field.nested_fields || []).map((f, idx) => idx === i ? val : f));
  const removeNested = (i) =>
    set("nested_fields", (field.nested_fields || []).filter((_, idx) => idx !== i));

  const nestedNames = (field.nested_fields || []).map(f => f.name);

  const borderColor = isDuplicate ? "#ef4444"
    : field.required ? "#6366f1"
    : "var(--border)";

  const bgColor = field.required
    ? "linear-gradient(to right, #f8f9ff 0px, #f8f9ff 3px, var(--bg-card) 3px)"
    : "var(--bg-card)";

  return (
    <div style={{ marginLeft: depth * 20, marginBottom: 8 }}>
      <div style={{
        border: `1px solid ${borderColor}`,
        borderRadius: "var(--radius-sm)",
        background: bgColor,
        overflow: "hidden",
        boxShadow: field.required ? "0 0 0 1px #e0e7ff" : undefined,
      }}>
        {/* Field header row */}
        <div style={{ display: "flex", alignItems: "center", gap: 8,
          padding: "8px 12px", cursor: "pointer",
          borderBottom: expanded ? "1px solid var(--border)" : "none" }}
          onClick={() => setExpanded(e => !e)}>

          <span style={{ fontSize: 11, color: "var(--text-muted)",
            transition: "transform 0.15s",
            transform: expanded ? "rotate(90deg)" : "rotate(0deg)" }}>▶</span>

          {/* Field name preview */}
          <code style={{ fontSize: 13, fontWeight: 600, color: "var(--c-primary)",
            flex: 1, minWidth: 0, overflow: "hidden",
            textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
            {field.name || <span style={{ color: "var(--text-muted)", fontStyle: "italic" }}>unnamed</span>}
          </code>

          <TypeBadge type={field.field_type || "string"} />
          <RequiredIndicator required={field.required} />

          <button type="button" onClick={e => { e.stopPropagation(); onRemove(); }}
            className="btn btn-ghost btn-sm btn-icon"
            style={{ color: "var(--c-danger)", padding: "2px 6px", flexShrink: 0 }}>
            ×
          </button>
        </div>

        {/* Expanded editor */}
        {expanded && (
          <div style={{ padding: "12px 14px", display: "flex",
            flexDirection: "column", gap: 12 }}>

            <div className="grid-2">
              {/* Name */}
              <div className="form-group">
                <label className="form-label" style={{ fontSize: 11 }}>
                  Field name <span className="form-required">*</span>
                  <TooltipIcon text={TIPS.name} />
                </label>
                <input
                  className={`form-control ${isDuplicate ? "error" : ""}`}
                  value={field.name}
                  onChange={e => set("name", e.target.value)}
                  placeholder="e.g. customer_id"
                  style={{ fontFamily: "monospace", fontSize: 13 }}
                />
                {isDuplicate && (
                  <span className="form-error">Duplicate field name</span>
                )}
              </div>

              {/* Type */}
              <div className="form-group">
                <label className="form-label" style={{ fontSize: 11 }}>
                  Type <TooltipIcon text={TIPS.field_type} />
                </label>
                <select className="form-control" value={field.field_type || "string"}
                  onChange={e => set("field_type", e.target.value)}
                  style={{ fontSize: 13 }}>
                  {FIELD_TYPES.map(t => (
                    <option key={t} value={t}>{t}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Description */}
            <div className="form-group">
              <label className="form-label" style={{ fontSize: 11 }}>
                Description (LLM hint) <span className="form-required">*</span>
                <TooltipIcon text={TIPS.description} />
              </label>
              <textarea
                className={`form-control ${!field.description?.trim() ? "error" : ""}`}
                value={field.description}
                onChange={e => set("description", e.target.value)}
                placeholder="e.g. The user's account number in format ACC-XXXXX, extracted from customer context"
                rows={2}
                style={{ fontSize: 13, resize: "vertical" }}
              />
              {!field.description?.trim() && (
                <span className="form-error">Description is required</span>
              )}
            </div>

            <div className="grid-2">
              {/* Required toggle */}
              <div className="form-group">
                <label className="form-label" style={{ fontSize: 11 }}>
                  Required <TooltipIcon text={TIPS.required} />
                </label>
                <div style={{ display: "flex", alignItems: "center", gap: 10, paddingTop: 4 }}>
                  <button
                    type="button"
                    onClick={() => set("required", !field.required)}
                    style={{
                      width: 42, height: 22, borderRadius: 99,
                      background: field.required ? "var(--c-primary)" : "var(--border)",
                      border: "none", cursor: "pointer",
                      position: "relative", transition: "background 0.2s",
                      flexShrink: 0,
                    }}
                  >
                    <span style={{
                      position: "absolute", top: 2,
                      left: field.required ? 22 : 2,
                      width: 18, height: 18, borderRadius: "50%",
                      background: "#fff", transition: "left 0.2s",
                      boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
                    }} />
                  </button>
                  <span style={{ fontSize: 12, color: field.required ? "var(--c-primary-text)" : "var(--text-muted)" }}>
                    {field.required ? "Required — must be present" : "Optional — include if confident"}
                  </span>
                </div>
              </div>

              {/* Default value */}
              <div className="form-group">
                <label className="form-label" style={{ fontSize: 11 }}>
                  Default value <TooltipIcon text={TIPS.default} />
                </label>
                <input
                  className="form-control"
                  value={field.default ?? ""}
                  onChange={e => set("default", e.target.value || null)}
                  placeholder={field.required ? "Fallback if LLM can't infer" : "Optional default"}
                  style={{ fontSize: 13 }}
                />
              </div>
            </div>

            {/* Nested fields for object type */}
            {field.field_type === "object" && (
              <div style={{ marginTop: 4 }}>
                <div style={{ display: "flex", alignItems: "center",
                  justifyContent: "space-between", marginBottom: 8 }}>
                  <label className="form-label" style={{ marginBottom: 0, fontSize: 11 }}>
                    Nested fields <TooltipIcon text={TIPS.nested} />
                    {(field.nested_fields || []).length > 0 && (
                      <span style={{ marginLeft: 6, fontSize: 10, color: "var(--text-muted)" }}>
                        {(field.nested_fields || []).length} defined
                      </span>
                    )}
                  </label>
                  <button type="button" className="btn btn-secondary btn-sm"
                    onClick={addNestedField} style={{ fontSize: 11 }}>
                    + Add nested field
                  </button>
                </div>
                {(field.nested_fields || []).map((nf, i) => (
                  <FieldEditor
                    key={i}
                    field={nf}
                    depth={depth + 1}
                    onChange={v => updateNested(i, v)}
                    onRemove={() => removeNested(i)}
                    allFieldNames={allFieldNames}
                    siblingNames={nestedNames}
                  />
                ))}
                {(field.nested_fields || []).length === 0 && (
                  <div style={{ padding: "10px 12px", borderRadius: "var(--radius-sm)",
                    border: "1px dashed var(--border)", textAlign: "center",
                    fontSize: 12, color: "var(--text-muted)" }}>
                    No nested fields. Add sub-fields for this object.
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Main schema editor ────────────────────────────────────────────────────────

const EMPTY_FIELD = () => ({
  name: "", description: "", required: true,
  field_type: "string", default: null, nested_fields: [],
});

export default function RequestSchemaEditor({ schema, onChange }) {
  const fields      = schema?.fields      || [];
  const strict      = schema?.strict      ?? true;
  const json_schema = schema?.json_schema || null;
  const [jsonSchemaText, setJsonSchemaText] = useState(
    json_schema ? JSON.stringify(json_schema, null, 2) : ""
  );
  const [jsonSchemaError, setJsonSchemaError] = useState("");
  const [showJsonSchema, setShowJsonSchema]   = useState(false);

  const update = (patch) => onChange({ ...schema, ...patch });

  const addField    = () => update({ fields: [...fields, EMPTY_FIELD()] });
  const updateField = (i, val) =>
    update({ fields: fields.map((f, idx) => idx === i ? val : f) });
  const removeField = (i) =>
    update({ fields: fields.filter((_, idx) => idx !== i) });

  const allNames    = fields.map(f => f.name);
  const hasErrors   = fields.some(f =>
    !f.name.trim() || !f.description.trim() ||
    allNames.filter(n => n === f.name).length > 1
  );

  const requiredFields  = fields.filter(f => f.required);
  const optionalFields  = fields.filter(f => !f.required);

  const handleJsonSchemaChange = (text) => {
    setJsonSchemaText(text);
    if (!text.trim()) {
      setJsonSchemaError("");
      update({ json_schema: null });
      return;
    }
    try {
      const parsed = JSON.parse(text);
      setJsonSchemaError("");
      update({ json_schema: parsed });
    } catch {
      setJsonSchemaError("Invalid JSON — fix before saving");
    }
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>

      {/* Header row */}
      <div style={{ display: "flex", alignItems: "center",
        justifyContent: "space-between", flexWrap: "wrap", gap: 10 }}>
        <div>
          <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 3 }}>
            Request schema fields
            {fields.length > 0 && (
              <span style={{ marginLeft: 8, fontSize: 12, fontWeight: 400,
                color: "var(--text-muted)" }}>
                {requiredFields.length} required · {optionalFields.length} optional
              </span>
            )}
          </div>
          <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>
            Define the fields the LLM mapper should populate at runtime.
            Required fields must always be present. Optional fields are included only when
            high-confidence context exists.
          </div>
        </div>
        <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
          {/* Strict mode toggle */}
          <label style={{ display: "flex", alignItems: "center", gap: 6,
            fontSize: 12, cursor: "pointer", color: "var(--text-secondary)" }}>
            <TooltipIcon text={TIPS.strict} />
            <span>Strict mode</span>
            <button
              type="button"
              onClick={() => update({ strict: !strict })}
              style={{
                width: 36, height: 18, borderRadius: 99,
                background: strict ? "var(--c-primary)" : "var(--border)",
                border: "none", cursor: "pointer", position: "relative",
                flexShrink: 0, transition: "background 0.2s",
              }}
            >
              <span style={{
                position: "absolute", top: 1, left: strict ? 18 : 1,
                width: 16, height: 16, borderRadius: "50%",
                background: "#fff", transition: "left 0.2s",
                boxShadow: "0 1px 2px rgba(0,0,0,.2)",
              }} />
            </button>
          </label>

          <button type="button" className="btn btn-primary btn-sm" onClick={addField}>
            + Add field
          </button>
        </div>
      </div>

      {/* Validation summary */}
      {hasErrors && fields.length > 0 && (
        <div style={{ padding: "8px 12px", borderRadius: "var(--radius-sm)",
          background: "#fff7ed", border: "1px solid #fed7aa",
          fontSize: 12, color: "#92400e" }}>
          ⚠ Some fields have validation errors. Fix them before saving.
        </div>
      )}

      {/* Empty state */}
      {fields.length === 0 ? (
        <div style={{ padding: "32px 24px", borderRadius: "var(--radius-sm)",
          border: "2px dashed var(--border)", textAlign: "center",
          display: "flex", flexDirection: "column", alignItems: "center", gap: 12 }}>
          <div style={{ fontSize: 28 }}>🗂</div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>No schema fields defined</div>
          <div style={{ fontSize: 13, color: "var(--text-muted)", maxWidth: 380, lineHeight: 1.6 }}>
            Add fields to enable schema-driven body construction. The LLM will
            intelligently populate each field from runtime context. Without fields,
            the legacy body_template renderer is used.
          </div>
          <button type="button" className="btn btn-primary btn-sm" onClick={addField}>
            + Add first field
          </button>
        </div>
      ) : (
        <div>
          {fields.map((field, i) => (
            <FieldEditor
              key={i}
              field={field}
              depth={0}
              onChange={v => updateField(i, v)}
              onRemove={() => removeField(i)}
              allFieldNames={allNames}
              siblingNames={allNames}
            />
          ))}
        </div>
      )}

      {/* Schema preview */}
      {fields.length > 0 && (
        <div style={{ padding: "12px 14px", borderRadius: "var(--radius-sm)",
          background: "#0f172a", border: "1px solid #1e293b" }}>
          <div style={{ fontSize: 10, fontWeight: 600, color: "#64748b",
            textTransform: "uppercase", letterSpacing: ".06em", marginBottom: 8 }}>
            Schema preview (stored in registry)
          </div>
          <pre style={{ fontSize: 11, color: "#e2e8f0", margin: 0, lineHeight: 1.6,
            fontFamily: "'SF Mono', 'Fira Code', monospace",
            whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
            {JSON.stringify({ fields, strict }, null, 2)}
          </pre>
        </div>
      )}

      {/* JSON Schema validation (advanced) */}
      <div>
        <button type="button" className="btn btn-ghost btn-sm"
          style={{ fontSize: 12, color: "var(--text-muted)" }}
          onClick={() => setShowJsonSchema(s => !s)}>
          {showJsonSchema ? "▼" : "▶"} Advanced: JSON Schema validation
          <TooltipIcon text={TIPS.json_schema} />
        </button>
        {showJsonSchema && (
          <div style={{ marginTop: 10 }}>
            <textarea
              className={`form-control ${jsonSchemaError ? "error" : ""}`}
              value={jsonSchemaText}
              onChange={e => handleJsonSchemaChange(e.target.value)}
              placeholder='{"type": "object", "required": ["field1"], "properties": {"field1": {"type": "string"}}}'
              rows={6}
              style={{ fontFamily: "monospace", fontSize: 12 }}
            />
            {jsonSchemaError && (
              <span className="form-error">{jsonSchemaError}</span>
            )}
            {!jsonSchemaError && json_schema && (
              <span className="form-hint" style={{ color: "var(--c-success-text)" }}>
                ✓ Valid JSON Schema — applied after LLM mapping
              </span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
